// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prdb_return_placevector.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_prdb_5freturn_5fplacevector_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_prdb_5freturn_5fplacevector_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "prdb_meta.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_prdb_5freturn_5fplacevector_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_prdb_5freturn_5fplacevector_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_prdb_5freturn_5fplacevector_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_prdb_5freturn_5fplacevector_2eproto_metadata_getter(int index);
namespace prdb {
namespace placevector {
class Data_t;
struct Data_tDefaultTypeInternal;
extern Data_tDefaultTypeInternal _Data_t_default_instance_;
class PlaceVectorR;
struct PlaceVectorRDefaultTypeInternal;
extern PlaceVectorRDefaultTypeInternal _PlaceVectorR_default_instance_;
}  // namespace placevector
}  // namespace prdb
PROTOBUF_NAMESPACE_OPEN
template<> ::prdb::placevector::Data_t* Arena::CreateMaybeMessage<::prdb::placevector::Data_t>(Arena*);
template<> ::prdb::placevector::PlaceVectorR* Arena::CreateMaybeMessage<::prdb::placevector::PlaceVectorR>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace prdb {
namespace placevector {

// ===================================================================

class Data_t PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:prdb.placevector.Data_t) */ {
 public:
  inline Data_t() : Data_t(nullptr) {}
  virtual ~Data_t();
  explicit constexpr Data_t(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Data_t(const Data_t& from);
  Data_t(Data_t&& from) noexcept
    : Data_t() {
    *this = ::std::move(from);
  }

  inline Data_t& operator=(const Data_t& from) {
    CopyFrom(from);
    return *this;
  }
  inline Data_t& operator=(Data_t&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Data_t& default_instance() {
    return *internal_default_instance();
  }
  static inline const Data_t* internal_default_instance() {
    return reinterpret_cast<const Data_t*>(
               &_Data_t_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Data_t& a, Data_t& b) {
    a.Swap(&b);
  }
  inline void Swap(Data_t* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Data_t* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Data_t* New() const final {
    return CreateMaybeMessage<Data_t>(nullptr);
  }

  Data_t* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Data_t>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Data_t& from);
  void MergeFrom(const Data_t& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Data_t* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "prdb.placevector.Data_t";
  }
  protected:
  explicit Data_t(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_prdb_5freturn_5fplacevector_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStMetaFieldNumber = 1,
    kF32DistanceFieldNumber = 2,
  };
  // .prdb.meta.Meta_t stMeta = 1;
  bool has_stmeta() const;
  private:
  bool _internal_has_stmeta() const;
  public:
  void clear_stmeta();
  const ::prdb::meta::Meta_t& stmeta() const;
  ::prdb::meta::Meta_t* release_stmeta();
  ::prdb::meta::Meta_t* mutable_stmeta();
  void set_allocated_stmeta(::prdb::meta::Meta_t* stmeta);
  private:
  const ::prdb::meta::Meta_t& _internal_stmeta() const;
  ::prdb::meta::Meta_t* _internal_mutable_stmeta();
  public:
  void unsafe_arena_set_allocated_stmeta(
      ::prdb::meta::Meta_t* stmeta);
  ::prdb::meta::Meta_t* unsafe_arena_release_stmeta();

  // float f32Distance = 2;
  void clear_f32distance();
  float f32distance() const;
  void set_f32distance(float value);
  private:
  float _internal_f32distance() const;
  void _internal_set_f32distance(float value);
  public:

  // @@protoc_insertion_point(class_scope:prdb.placevector.Data_t)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::prdb::meta::Meta_t* stmeta_;
  float f32distance_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_prdb_5freturn_5fplacevector_2eproto;
};
// -------------------------------------------------------------------

class PlaceVectorR PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:prdb.placevector.PlaceVectorR) */ {
 public:
  inline PlaceVectorR() : PlaceVectorR(nullptr) {}
  virtual ~PlaceVectorR();
  explicit constexpr PlaceVectorR(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlaceVectorR(const PlaceVectorR& from);
  PlaceVectorR(PlaceVectorR&& from) noexcept
    : PlaceVectorR() {
    *this = ::std::move(from);
  }

  inline PlaceVectorR& operator=(const PlaceVectorR& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlaceVectorR& operator=(PlaceVectorR&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PlaceVectorR& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlaceVectorR* internal_default_instance() {
    return reinterpret_cast<const PlaceVectorR*>(
               &_PlaceVectorR_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PlaceVectorR& a, PlaceVectorR& b) {
    a.Swap(&b);
  }
  inline void Swap(PlaceVectorR* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlaceVectorR* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PlaceVectorR* New() const final {
    return CreateMaybeMessage<PlaceVectorR>(nullptr);
  }

  PlaceVectorR* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PlaceVectorR>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PlaceVectorR& from);
  void MergeFrom(const PlaceVectorR& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlaceVectorR* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "prdb.placevector.PlaceVectorR";
  }
  protected:
  explicit PlaceVectorR(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_prdb_5freturn_5fplacevector_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStDataFieldNumber = 1,
  };
  // repeated .prdb.placevector.Data_t stData = 1;
  int stdata_size() const;
  private:
  int _internal_stdata_size() const;
  public:
  void clear_stdata();
  ::prdb::placevector::Data_t* mutable_stdata(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::prdb::placevector::Data_t >*
      mutable_stdata();
  private:
  const ::prdb::placevector::Data_t& _internal_stdata(int index) const;
  ::prdb::placevector::Data_t* _internal_add_stdata();
  public:
  const ::prdb::placevector::Data_t& stdata(int index) const;
  ::prdb::placevector::Data_t* add_stdata();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::prdb::placevector::Data_t >&
      stdata() const;

  // @@protoc_insertion_point(class_scope:prdb.placevector.PlaceVectorR)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::prdb::placevector::Data_t > stdata_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_prdb_5freturn_5fplacevector_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Data_t

// .prdb.meta.Meta_t stMeta = 1;
inline bool Data_t::_internal_has_stmeta() const {
  return this != internal_default_instance() && stmeta_ != nullptr;
}
inline bool Data_t::has_stmeta() const {
  return _internal_has_stmeta();
}
inline const ::prdb::meta::Meta_t& Data_t::_internal_stmeta() const {
  const ::prdb::meta::Meta_t* p = stmeta_;
  return p != nullptr ? *p : reinterpret_cast<const ::prdb::meta::Meta_t&>(
      ::prdb::meta::_Meta_t_default_instance_);
}
inline const ::prdb::meta::Meta_t& Data_t::stmeta() const {
  // @@protoc_insertion_point(field_get:prdb.placevector.Data_t.stMeta)
  return _internal_stmeta();
}
inline void Data_t::unsafe_arena_set_allocated_stmeta(
    ::prdb::meta::Meta_t* stmeta) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(stmeta_);
  }
  stmeta_ = stmeta;
  if (stmeta) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:prdb.placevector.Data_t.stMeta)
}
inline ::prdb::meta::Meta_t* Data_t::release_stmeta() {
  
  ::prdb::meta::Meta_t* temp = stmeta_;
  stmeta_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::prdb::meta::Meta_t* Data_t::unsafe_arena_release_stmeta() {
  // @@protoc_insertion_point(field_release:prdb.placevector.Data_t.stMeta)
  
  ::prdb::meta::Meta_t* temp = stmeta_;
  stmeta_ = nullptr;
  return temp;
}
inline ::prdb::meta::Meta_t* Data_t::_internal_mutable_stmeta() {
  
  if (stmeta_ == nullptr) {
    auto* p = CreateMaybeMessage<::prdb::meta::Meta_t>(GetArena());
    stmeta_ = p;
  }
  return stmeta_;
}
inline ::prdb::meta::Meta_t* Data_t::mutable_stmeta() {
  // @@protoc_insertion_point(field_mutable:prdb.placevector.Data_t.stMeta)
  return _internal_mutable_stmeta();
}
inline void Data_t::set_allocated_stmeta(::prdb::meta::Meta_t* stmeta) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(stmeta_);
  }
  if (stmeta) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(stmeta)->GetArena();
    if (message_arena != submessage_arena) {
      stmeta = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, stmeta, submessage_arena);
    }
    
  } else {
    
  }
  stmeta_ = stmeta;
  // @@protoc_insertion_point(field_set_allocated:prdb.placevector.Data_t.stMeta)
}

// float f32Distance = 2;
inline void Data_t::clear_f32distance() {
  f32distance_ = 0;
}
inline float Data_t::_internal_f32distance() const {
  return f32distance_;
}
inline float Data_t::f32distance() const {
  // @@protoc_insertion_point(field_get:prdb.placevector.Data_t.f32Distance)
  return _internal_f32distance();
}
inline void Data_t::_internal_set_f32distance(float value) {
  
  f32distance_ = value;
}
inline void Data_t::set_f32distance(float value) {
  _internal_set_f32distance(value);
  // @@protoc_insertion_point(field_set:prdb.placevector.Data_t.f32Distance)
}

// -------------------------------------------------------------------

// PlaceVectorR

// repeated .prdb.placevector.Data_t stData = 1;
inline int PlaceVectorR::_internal_stdata_size() const {
  return stdata_.size();
}
inline int PlaceVectorR::stdata_size() const {
  return _internal_stdata_size();
}
inline void PlaceVectorR::clear_stdata() {
  stdata_.Clear();
}
inline ::prdb::placevector::Data_t* PlaceVectorR::mutable_stdata(int index) {
  // @@protoc_insertion_point(field_mutable:prdb.placevector.PlaceVectorR.stData)
  return stdata_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::prdb::placevector::Data_t >*
PlaceVectorR::mutable_stdata() {
  // @@protoc_insertion_point(field_mutable_list:prdb.placevector.PlaceVectorR.stData)
  return &stdata_;
}
inline const ::prdb::placevector::Data_t& PlaceVectorR::_internal_stdata(int index) const {
  return stdata_.Get(index);
}
inline const ::prdb::placevector::Data_t& PlaceVectorR::stdata(int index) const {
  // @@protoc_insertion_point(field_get:prdb.placevector.PlaceVectorR.stData)
  return _internal_stdata(index);
}
inline ::prdb::placevector::Data_t* PlaceVectorR::_internal_add_stdata() {
  return stdata_.Add();
}
inline ::prdb::placevector::Data_t* PlaceVectorR::add_stdata() {
  // @@protoc_insertion_point(field_add:prdb.placevector.PlaceVectorR.stData)
  return _internal_add_stdata();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::prdb::placevector::Data_t >&
PlaceVectorR::stdata() const {
  // @@protoc_insertion_point(field_list:prdb.placevector.PlaceVectorR.stData)
  return stdata_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace placevector
}  // namespace prdb

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_prdb_5freturn_5fplacevector_2eproto
