// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package VPResult

import (
	context "context"
	SensorData "github.com/sysmoon/vps-grpc-gateway/schema/SensorData"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LocationServiceClient is the client API for LocationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LocationServiceClient interface {
	GetLocationPose(ctx context.Context, in *SensorData.VPData, opts ...grpc.CallOption) (*VPServiceT, error)
	GetLocationInfo(ctx context.Context, in *SensorData.VPData, opts ...grpc.CallOption) (*wrapperspb.FloatValue, error)
}

type locationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLocationServiceClient(cc grpc.ClientConnInterface) LocationServiceClient {
	return &locationServiceClient{cc}
}

func (c *locationServiceClient) GetLocationPose(ctx context.Context, in *SensorData.VPData, opts ...grpc.CallOption) (*VPServiceT, error) {
	out := new(VPServiceT)
	err := c.cc.Invoke(ctx, "/vpresult.LocationService/getLocationPose", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) GetLocationInfo(ctx context.Context, in *SensorData.VPData, opts ...grpc.CallOption) (*wrapperspb.FloatValue, error) {
	out := new(wrapperspb.FloatValue)
	err := c.cc.Invoke(ctx, "/vpresult.LocationService/getLocationInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocationServiceServer is the server API for LocationService service.
// All implementations must embed UnimplementedLocationServiceServer
// for forward compatibility
type LocationServiceServer interface {
	GetLocationPose(context.Context, *SensorData.VPData) (*VPServiceT, error)
	GetLocationInfo(context.Context, *SensorData.VPData) (*wrapperspb.FloatValue, error)
	mustEmbedUnimplementedLocationServiceServer()
}

// UnimplementedLocationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLocationServiceServer struct {
}

func (UnimplementedLocationServiceServer) GetLocationPose(context.Context, *SensorData.VPData) (*VPServiceT, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocationPose not implemented")
}
func (UnimplementedLocationServiceServer) GetLocationInfo(context.Context, *SensorData.VPData) (*wrapperspb.FloatValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocationInfo not implemented")
}
func (UnimplementedLocationServiceServer) mustEmbedUnimplementedLocationServiceServer() {}

// UnsafeLocationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocationServiceServer will
// result in compilation errors.
type UnsafeLocationServiceServer interface {
	mustEmbedUnimplementedLocationServiceServer()
}

func RegisterLocationServiceServer(s grpc.ServiceRegistrar, srv LocationServiceServer) {
	s.RegisterService(&LocationService_ServiceDesc, srv)
}

func _LocationService_GetLocationPose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensorData.VPData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).GetLocationPose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vpresult.LocationService/getLocationPose",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).GetLocationPose(ctx, req.(*SensorData.VPData))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_GetLocationInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensorData.VPData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).GetLocationInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vpresult.LocationService/getLocationInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).GetLocationInfo(ctx, req.(*SensorData.VPData))
	}
	return interceptor(ctx, in, info, handler)
}

// LocationService_ServiceDesc is the grpc.ServiceDesc for LocationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vpresult.LocationService",
	HandlerType: (*LocationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getLocationPose",
			Handler:    _LocationService_GetLocationPose_Handler,
		},
		{
			MethodName: "getLocationInfo",
			Handler:    _LocationService_GetLocationInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schema/VPResult/vpresult.proto",
}
