# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lfsppdb_return_localfeature.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import prdb_meta_pb2 as prdb__meta__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lfsppdb_return_localfeature.proto',
  package='lfsppdb.localfeature',
  syntax='proto3',
  serialized_options=b'\n\014dbms.lfsppdb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!lfsppdb_return_localfeature.proto\x12\x14lfsppdb.localfeature\x1a\x0fprdb_meta.proto\"\xd4\x01\n\tMatched_t\x12\x1f\n\x17u16MatchedKeyPointIndex\x18\x01 \x01(\r\x12\x35\n\x19stf32MatchedKeyPointWorld\x18\x02 \x01(\x0b\x32\x12.prdb.meta.XYZ32_t\x12\x34\n\x16stMatchedKeyPointImage\x18\x03 \x01(\x0b\x32\x14.prdb.meta.UVPoint_t\x12\x13\n\x0b\x66\x33\x32\x44istance\x18\x04 \x01(\x02\x12$\n\x1cu8MatchedKeypointLocationIdx\x18\x05 \x01(\r\"g\n\x0cQueryMatch_t\x12\x1f\n\x17u16QueriedKeyPointIndex\x18\x01 \x01(\r\x12\x36\n\rstMatchedTopK\x18\x02 \x03(\x0b\x32\x1f.lfsppdb.localfeature.Matched_t\"\x94\x01\n\x06\x44\x61ta_t\x12\x1f\n\x17u64QueriedKeyFrameIndex\x18\x01 \x01(\x04\x12/\n\x13stReferenceLocation\x18\x02 \x01(\x0b\x32\x12.prdb.meta.XYZ64_t\x12\x38\n\x0cstQueryMatch\x18\x03 \x03(\x0b\x32\".lfsppdb.localfeature.QueryMatch_t\"=\n\rLocalFeatureR\x12,\n\x06stData\x18\x01 \x03(\x0b\x32\x1c.lfsppdb.localfeature.Data_tB\x0e\n\x0c\x64\x62ms.lfsppdbb\x06proto3'
  ,
  dependencies=[prdb__meta__pb2.DESCRIPTOR,])




_MATCHED_T = _descriptor.Descriptor(
  name='Matched_t',
  full_name='lfsppdb.localfeature.Matched_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='u16MatchedKeyPointIndex', full_name='lfsppdb.localfeature.Matched_t.u16MatchedKeyPointIndex', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stf32MatchedKeyPointWorld', full_name='lfsppdb.localfeature.Matched_t.stf32MatchedKeyPointWorld', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stMatchedKeyPointImage', full_name='lfsppdb.localfeature.Matched_t.stMatchedKeyPointImage', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='f32Distance', full_name='lfsppdb.localfeature.Matched_t.f32Distance', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='u8MatchedKeypointLocationIdx', full_name='lfsppdb.localfeature.Matched_t.u8MatchedKeypointLocationIdx', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=289,
)


_QUERYMATCH_T = _descriptor.Descriptor(
  name='QueryMatch_t',
  full_name='lfsppdb.localfeature.QueryMatch_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='u16QueriedKeyPointIndex', full_name='lfsppdb.localfeature.QueryMatch_t.u16QueriedKeyPointIndex', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stMatchedTopK', full_name='lfsppdb.localfeature.QueryMatch_t.stMatchedTopK', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=394,
)


_DATA_T = _descriptor.Descriptor(
  name='Data_t',
  full_name='lfsppdb.localfeature.Data_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='u64QueriedKeyFrameIndex', full_name='lfsppdb.localfeature.Data_t.u64QueriedKeyFrameIndex', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stReferenceLocation', full_name='lfsppdb.localfeature.Data_t.stReferenceLocation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stQueryMatch', full_name='lfsppdb.localfeature.Data_t.stQueryMatch', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=545,
)


_LOCALFEATURER = _descriptor.Descriptor(
  name='LocalFeatureR',
  full_name='lfsppdb.localfeature.LocalFeatureR',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stData', full_name='lfsppdb.localfeature.LocalFeatureR.stData', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=547,
  serialized_end=608,
)

_MATCHED_T.fields_by_name['stf32MatchedKeyPointWorld'].message_type = prdb__meta__pb2._XYZ32_T
_MATCHED_T.fields_by_name['stMatchedKeyPointImage'].message_type = prdb__meta__pb2._UVPOINT_T
_QUERYMATCH_T.fields_by_name['stMatchedTopK'].message_type = _MATCHED_T
_DATA_T.fields_by_name['stReferenceLocation'].message_type = prdb__meta__pb2._XYZ64_T
_DATA_T.fields_by_name['stQueryMatch'].message_type = _QUERYMATCH_T
_LOCALFEATURER.fields_by_name['stData'].message_type = _DATA_T
DESCRIPTOR.message_types_by_name['Matched_t'] = _MATCHED_T
DESCRIPTOR.message_types_by_name['QueryMatch_t'] = _QUERYMATCH_T
DESCRIPTOR.message_types_by_name['Data_t'] = _DATA_T
DESCRIPTOR.message_types_by_name['LocalFeatureR'] = _LOCALFEATURER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Matched_t = _reflection.GeneratedProtocolMessageType('Matched_t', (_message.Message,), {
  'DESCRIPTOR' : _MATCHED_T,
  '__module__' : 'lfsppdb_return_localfeature_pb2'
  # @@protoc_insertion_point(class_scope:lfsppdb.localfeature.Matched_t)
  })
_sym_db.RegisterMessage(Matched_t)

QueryMatch_t = _reflection.GeneratedProtocolMessageType('QueryMatch_t', (_message.Message,), {
  'DESCRIPTOR' : _QUERYMATCH_T,
  '__module__' : 'lfsppdb_return_localfeature_pb2'
  # @@protoc_insertion_point(class_scope:lfsppdb.localfeature.QueryMatch_t)
  })
_sym_db.RegisterMessage(QueryMatch_t)

Data_t = _reflection.GeneratedProtocolMessageType('Data_t', (_message.Message,), {
  'DESCRIPTOR' : _DATA_T,
  '__module__' : 'lfsppdb_return_localfeature_pb2'
  # @@protoc_insertion_point(class_scope:lfsppdb.localfeature.Data_t)
  })
_sym_db.RegisterMessage(Data_t)

LocalFeatureR = _reflection.GeneratedProtocolMessageType('LocalFeatureR', (_message.Message,), {
  'DESCRIPTOR' : _LOCALFEATURER,
  '__module__' : 'lfsppdb_return_localfeature_pb2'
  # @@protoc_insertion_point(class_scope:lfsppdb.localfeature.LocalFeatureR)
  })
_sym_db.RegisterMessage(LocalFeatureR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
