// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PoseEstimation.proto

#include "PoseEstimation.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace vlam {
namespace pe {
constexpr PoseEstimationIn::PoseEstimationIn(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : stvpsensordata_(nullptr)
  , arstplacevectorlist_(nullptr)
  , arstlocalfeaturelist_(nullptr){}
struct PoseEstimationInDefaultTypeInternal {
  constexpr PoseEstimationInDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~PoseEstimationInDefaultTypeInternal() {}
  union {
    PoseEstimationIn _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PoseEstimationInDefaultTypeInternal _PoseEstimationIn_default_instance_;
}  // namespace pe
}  // namespace vlam
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_PoseEstimation_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_PoseEstimation_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_PoseEstimation_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_PoseEstimation_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::vlam::pe::PoseEstimationIn, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::vlam::pe::PoseEstimationIn, stvpsensordata_),
  PROTOBUF_FIELD_OFFSET(::vlam::pe::PoseEstimationIn, arstplacevectorlist_),
  PROTOBUF_FIELD_OFFSET(::vlam::pe::PoseEstimationIn, arstlocalfeaturelist_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::vlam::pe::PoseEstimationIn)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::vlam::pe::_PoseEstimationIn_default_instance_),
};

const char descriptor_table_protodef_PoseEstimation_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024PoseEstimation.proto\022\007vlam.pe\032\021placeve"
  "ctor.proto\032\022localfeature.proto\032\014vp_msg.p"
  "roto\"\246\001\n\020PoseEstimationIn\022&\n\016stVPSensorD"
  "ata\030\001 \001(\0132\016.vpdata.VPData\0223\n\023arstPlaceVe"
  "ctorList\030\013 \001(\0132\026.VgeoDB.PlaceVectorSet\0225"
  "\n\024arstLocalFeatureList\030\014 \001(\0132\027.VgeoDB.Lo"
  "calFeatureSetB\025\n\023vlam.poseestimationb\006pr"
  "oto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_PoseEstimation_2eproto_deps[3] = {
  &::descriptor_table_localfeature_2eproto,
  &::descriptor_table_placevector_2eproto,
  &::descriptor_table_vp_5fmsg_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_PoseEstimation_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_PoseEstimation_2eproto = {
  false, false, 284, descriptor_table_protodef_PoseEstimation_2eproto, "PoseEstimation.proto", 
  &descriptor_table_PoseEstimation_2eproto_once, descriptor_table_PoseEstimation_2eproto_deps, 3, 1,
  schemas, file_default_instances, TableStruct_PoseEstimation_2eproto::offsets,
  file_level_metadata_PoseEstimation_2eproto, file_level_enum_descriptors_PoseEstimation_2eproto, file_level_service_descriptors_PoseEstimation_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_PoseEstimation_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_PoseEstimation_2eproto);
  return descriptor_table_PoseEstimation_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_PoseEstimation_2eproto(&descriptor_table_PoseEstimation_2eproto);
namespace vlam {
namespace pe {

// ===================================================================

class PoseEstimationIn::_Internal {
 public:
  static const ::vpdata::VPData& stvpsensordata(const PoseEstimationIn* msg);
  static const ::VgeoDB::PlaceVectorSet& arstplacevectorlist(const PoseEstimationIn* msg);
  static const ::VgeoDB::LocalFeatureSet& arstlocalfeaturelist(const PoseEstimationIn* msg);
};

const ::vpdata::VPData&
PoseEstimationIn::_Internal::stvpsensordata(const PoseEstimationIn* msg) {
  return *msg->stvpsensordata_;
}
const ::VgeoDB::PlaceVectorSet&
PoseEstimationIn::_Internal::arstplacevectorlist(const PoseEstimationIn* msg) {
  return *msg->arstplacevectorlist_;
}
const ::VgeoDB::LocalFeatureSet&
PoseEstimationIn::_Internal::arstlocalfeaturelist(const PoseEstimationIn* msg) {
  return *msg->arstlocalfeaturelist_;
}
void PoseEstimationIn::clear_stvpsensordata() {
  if (GetArena() == nullptr && stvpsensordata_ != nullptr) {
    delete stvpsensordata_;
  }
  stvpsensordata_ = nullptr;
}
void PoseEstimationIn::clear_arstplacevectorlist() {
  if (GetArena() == nullptr && arstplacevectorlist_ != nullptr) {
    delete arstplacevectorlist_;
  }
  arstplacevectorlist_ = nullptr;
}
void PoseEstimationIn::clear_arstlocalfeaturelist() {
  if (GetArena() == nullptr && arstlocalfeaturelist_ != nullptr) {
    delete arstlocalfeaturelist_;
  }
  arstlocalfeaturelist_ = nullptr;
}
PoseEstimationIn::PoseEstimationIn(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:vlam.pe.PoseEstimationIn)
}
PoseEstimationIn::PoseEstimationIn(const PoseEstimationIn& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_stvpsensordata()) {
    stvpsensordata_ = new ::vpdata::VPData(*from.stvpsensordata_);
  } else {
    stvpsensordata_ = nullptr;
  }
  if (from._internal_has_arstplacevectorlist()) {
    arstplacevectorlist_ = new ::VgeoDB::PlaceVectorSet(*from.arstplacevectorlist_);
  } else {
    arstplacevectorlist_ = nullptr;
  }
  if (from._internal_has_arstlocalfeaturelist()) {
    arstlocalfeaturelist_ = new ::VgeoDB::LocalFeatureSet(*from.arstlocalfeaturelist_);
  } else {
    arstlocalfeaturelist_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:vlam.pe.PoseEstimationIn)
}

void PoseEstimationIn::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&stvpsensordata_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&arstlocalfeaturelist_) -
    reinterpret_cast<char*>(&stvpsensordata_)) + sizeof(arstlocalfeaturelist_));
}

PoseEstimationIn::~PoseEstimationIn() {
  // @@protoc_insertion_point(destructor:vlam.pe.PoseEstimationIn)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void PoseEstimationIn::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete stvpsensordata_;
  if (this != internal_default_instance()) delete arstplacevectorlist_;
  if (this != internal_default_instance()) delete arstlocalfeaturelist_;
}

void PoseEstimationIn::ArenaDtor(void* object) {
  PoseEstimationIn* _this = reinterpret_cast< PoseEstimationIn* >(object);
  (void)_this;
}
void PoseEstimationIn::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PoseEstimationIn::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void PoseEstimationIn::Clear() {
// @@protoc_insertion_point(message_clear_start:vlam.pe.PoseEstimationIn)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArena() == nullptr && stvpsensordata_ != nullptr) {
    delete stvpsensordata_;
  }
  stvpsensordata_ = nullptr;
  if (GetArena() == nullptr && arstplacevectorlist_ != nullptr) {
    delete arstplacevectorlist_;
  }
  arstplacevectorlist_ = nullptr;
  if (GetArena() == nullptr && arstlocalfeaturelist_ != nullptr) {
    delete arstlocalfeaturelist_;
  }
  arstlocalfeaturelist_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PoseEstimationIn::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .vpdata.VPData stVPSensorData = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_stvpsensordata(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .VgeoDB.PlaceVectorSet arstPlaceVectorList = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 90)) {
          ptr = ctx->ParseMessage(_internal_mutable_arstplacevectorlist(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .VgeoDB.LocalFeatureSet arstLocalFeatureList = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 98)) {
          ptr = ctx->ParseMessage(_internal_mutable_arstlocalfeaturelist(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PoseEstimationIn::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:vlam.pe.PoseEstimationIn)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .vpdata.VPData stVPSensorData = 1;
  if (this->has_stvpsensordata()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::stvpsensordata(this), target, stream);
  }

  // .VgeoDB.PlaceVectorSet arstPlaceVectorList = 11;
  if (this->has_arstplacevectorlist()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        11, _Internal::arstplacevectorlist(this), target, stream);
  }

  // .VgeoDB.LocalFeatureSet arstLocalFeatureList = 12;
  if (this->has_arstlocalfeaturelist()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        12, _Internal::arstlocalfeaturelist(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vlam.pe.PoseEstimationIn)
  return target;
}

size_t PoseEstimationIn::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:vlam.pe.PoseEstimationIn)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .vpdata.VPData stVPSensorData = 1;
  if (this->has_stvpsensordata()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *stvpsensordata_);
  }

  // .VgeoDB.PlaceVectorSet arstPlaceVectorList = 11;
  if (this->has_arstplacevectorlist()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *arstplacevectorlist_);
  }

  // .VgeoDB.LocalFeatureSet arstLocalFeatureList = 12;
  if (this->has_arstlocalfeaturelist()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *arstlocalfeaturelist_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PoseEstimationIn::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:vlam.pe.PoseEstimationIn)
  GOOGLE_DCHECK_NE(&from, this);
  const PoseEstimationIn* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PoseEstimationIn>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:vlam.pe.PoseEstimationIn)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:vlam.pe.PoseEstimationIn)
    MergeFrom(*source);
  }
}

void PoseEstimationIn::MergeFrom(const PoseEstimationIn& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:vlam.pe.PoseEstimationIn)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_stvpsensordata()) {
    _internal_mutable_stvpsensordata()->::vpdata::VPData::MergeFrom(from._internal_stvpsensordata());
  }
  if (from.has_arstplacevectorlist()) {
    _internal_mutable_arstplacevectorlist()->::VgeoDB::PlaceVectorSet::MergeFrom(from._internal_arstplacevectorlist());
  }
  if (from.has_arstlocalfeaturelist()) {
    _internal_mutable_arstlocalfeaturelist()->::VgeoDB::LocalFeatureSet::MergeFrom(from._internal_arstlocalfeaturelist());
  }
}

void PoseEstimationIn::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:vlam.pe.PoseEstimationIn)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PoseEstimationIn::CopyFrom(const PoseEstimationIn& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vlam.pe.PoseEstimationIn)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PoseEstimationIn::IsInitialized() const {
  return true;
}

void PoseEstimationIn::InternalSwap(PoseEstimationIn* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PoseEstimationIn, arstlocalfeaturelist_)
      + sizeof(PoseEstimationIn::arstlocalfeaturelist_)
      - PROTOBUF_FIELD_OFFSET(PoseEstimationIn, stvpsensordata_)>(
          reinterpret_cast<char*>(&stvpsensordata_),
          reinterpret_cast<char*>(&other->stvpsensordata_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PoseEstimationIn::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace pe
}  // namespace vlam
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::vlam::pe::PoseEstimationIn* Arena::CreateMaybeMessage< ::vlam::pe::PoseEstimationIn >(Arena* arena) {
  return Arena::CreateMessageInternal< ::vlam::pe::PoseEstimationIn >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
