// source: vp_state.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var vp_tracking_pb = require('./vp_tracking_pb.js');
goog.object.extend(proto, vp_tracking_pb);
goog.exportSymbol('proto.vpdata.state.VPState_t', null, global);
goog.exportSymbol('proto.vpdata.state.VPState_t.VPStatus', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vpdata.state.VPState_t = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.vpdata.state.VPState_t.repeatedFields_, null);
};
goog.inherits(proto.vpdata.state.VPState_t, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vpdata.state.VPState_t.displayName = 'proto.vpdata.state.VPState_t';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.vpdata.state.VPState_t.repeatedFields_ = [3,4,5,6,8,11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vpdata.state.VPState_t.prototype.toObject = function(opt_includeInstance) {
  return proto.vpdata.state.VPState_t.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vpdata.state.VPState_t} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vpdata.state.VPState_t.toObject = function(includeInstance, msg) {
  var f, obj = {
    evpstatus: jspb.Message.getFieldWithDefault(msg, 1, 0),
    u64tslastloc: jspb.Message.getFieldWithDefault(msg, 2, 0),
    arf64lastlocationList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 3)) == null ? undefined : f,
    arf32lastorientationList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 4)) == null ? undefined : f,
    arf32lastdrposeList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 5)) == null ? undefined : f,
    arf32curdrposeList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 6)) == null ? undefined : f,
    evpstatustrackingmode: jspb.Message.getFieldWithDefault(msg, 7, 0),
    stframeposeinfosetList: jspb.Message.toObjectList(msg.getStframeposeinfosetList(),
    vp_tracking_pb.FramePoseInfo_t.toObject, includeInstance),
    stlinearvelocitykf: (f = msg.getStlinearvelocitykf()) && vp_tracking_pb.KalmanFilter_t.toObject(includeInstance, f),
    stvpsposekf: (f = msg.getStvpsposekf()) && vp_tracking_pb.KalmanFilter_t.toObject(includeInstance, f),
    stparamsetList: jspb.Message.toObjectList(msg.getStparamsetList(),
    vp_tracking_pb.Param_t.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vpdata.state.VPState_t}
 */
proto.vpdata.state.VPState_t.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vpdata.state.VPState_t;
  return proto.vpdata.state.VPState_t.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vpdata.state.VPState_t} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vpdata.state.VPState_t}
 */
proto.vpdata.state.VPState_t.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.vpdata.state.VPState_t.VPStatus} */ (reader.readEnum());
      msg.setEvpstatus(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setU64tslastloc(value);
      break;
    case 3:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedDouble() : [reader.readDouble()]);
      for (var i = 0; i < values.length; i++) {
        msg.addArf64lastlocation(values[i]);
      }
      break;
    case 4:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedFloat() : [reader.readFloat()]);
      for (var i = 0; i < values.length; i++) {
        msg.addArf32lastorientation(values[i]);
      }
      break;
    case 5:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedFloat() : [reader.readFloat()]);
      for (var i = 0; i < values.length; i++) {
        msg.addArf32lastdrpose(values[i]);
      }
      break;
    case 6:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedFloat() : [reader.readFloat()]);
      for (var i = 0; i < values.length; i++) {
        msg.addArf32curdrpose(values[i]);
      }
      break;
    case 7:
      var value = /** @type {!proto.vp.tracking.VPStatusTrackingMode} */ (reader.readEnum());
      msg.setEvpstatustrackingmode(value);
      break;
    case 8:
      var value = new vp_tracking_pb.FramePoseInfo_t;
      reader.readMessage(value,vp_tracking_pb.FramePoseInfo_t.deserializeBinaryFromReader);
      msg.addStframeposeinfoset(value);
      break;
    case 9:
      var value = new vp_tracking_pb.KalmanFilter_t;
      reader.readMessage(value,vp_tracking_pb.KalmanFilter_t.deserializeBinaryFromReader);
      msg.setStlinearvelocitykf(value);
      break;
    case 10:
      var value = new vp_tracking_pb.KalmanFilter_t;
      reader.readMessage(value,vp_tracking_pb.KalmanFilter_t.deserializeBinaryFromReader);
      msg.setStvpsposekf(value);
      break;
    case 11:
      var value = new vp_tracking_pb.Param_t;
      reader.readMessage(value,vp_tracking_pb.Param_t.deserializeBinaryFromReader);
      msg.addStparamset(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vpdata.state.VPState_t.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vpdata.state.VPState_t.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vpdata.state.VPState_t} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vpdata.state.VPState_t.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEvpstatus();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getU64tslastloc();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getArf64lastlocationList();
  if (f.length > 0) {
    writer.writePackedDouble(
      3,
      f
    );
  }
  f = message.getArf32lastorientationList();
  if (f.length > 0) {
    writer.writePackedFloat(
      4,
      f
    );
  }
  f = message.getArf32lastdrposeList();
  if (f.length > 0) {
    writer.writePackedFloat(
      5,
      f
    );
  }
  f = message.getArf32curdrposeList();
  if (f.length > 0) {
    writer.writePackedFloat(
      6,
      f
    );
  }
  f = message.getEvpstatustrackingmode();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = message.getStframeposeinfosetList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      vp_tracking_pb.FramePoseInfo_t.serializeBinaryToWriter
    );
  }
  f = message.getStlinearvelocitykf();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      vp_tracking_pb.KalmanFilter_t.serializeBinaryToWriter
    );
  }
  f = message.getStvpsposekf();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      vp_tracking_pb.KalmanFilter_t.serializeBinaryToWriter
    );
  }
  f = message.getStparamsetList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      vp_tracking_pb.Param_t.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.vpdata.state.VPState_t.VPStatus = {
  EUNKNOWN_STATUS: 0,
  EINIT: 1,
  ETRACK: 2,
  ECOSTING: 3,
  EFAIL: 4
};

/**
 * optional VPStatus eVPStatus = 1;
 * @return {!proto.vpdata.state.VPState_t.VPStatus}
 */
proto.vpdata.state.VPState_t.prototype.getEvpstatus = function() {
  return /** @type {!proto.vpdata.state.VPState_t.VPStatus} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.vpdata.state.VPState_t.VPStatus} value
 * @return {!proto.vpdata.state.VPState_t} returns this
 */
proto.vpdata.state.VPState_t.prototype.setEvpstatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional uint64 u64TSLastLoc = 2;
 * @return {number}
 */
proto.vpdata.state.VPState_t.prototype.getU64tslastloc = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.vpdata.state.VPState_t} returns this
 */
proto.vpdata.state.VPState_t.prototype.setU64tslastloc = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * repeated double arf64LastLocation = 3;
 * @return {!Array<number>}
 */
proto.vpdata.state.VPState_t.prototype.getArf64lastlocationList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 3));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.vpdata.state.VPState_t} returns this
 */
proto.vpdata.state.VPState_t.prototype.setArf64lastlocationList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.vpdata.state.VPState_t} returns this
 */
proto.vpdata.state.VPState_t.prototype.addArf64lastlocation = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.vpdata.state.VPState_t} returns this
 */
proto.vpdata.state.VPState_t.prototype.clearArf64lastlocationList = function() {
  return this.setArf64lastlocationList([]);
};


/**
 * repeated float arf32LastOrientation = 4;
 * @return {!Array<number>}
 */
proto.vpdata.state.VPState_t.prototype.getArf32lastorientationList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 4));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.vpdata.state.VPState_t} returns this
 */
proto.vpdata.state.VPState_t.prototype.setArf32lastorientationList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.vpdata.state.VPState_t} returns this
 */
proto.vpdata.state.VPState_t.prototype.addArf32lastorientation = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.vpdata.state.VPState_t} returns this
 */
proto.vpdata.state.VPState_t.prototype.clearArf32lastorientationList = function() {
  return this.setArf32lastorientationList([]);
};


/**
 * repeated float arf32LastDRPose = 5;
 * @return {!Array<number>}
 */
proto.vpdata.state.VPState_t.prototype.getArf32lastdrposeList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 5));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.vpdata.state.VPState_t} returns this
 */
proto.vpdata.state.VPState_t.prototype.setArf32lastdrposeList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.vpdata.state.VPState_t} returns this
 */
proto.vpdata.state.VPState_t.prototype.addArf32lastdrpose = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.vpdata.state.VPState_t} returns this
 */
proto.vpdata.state.VPState_t.prototype.clearArf32lastdrposeList = function() {
  return this.setArf32lastdrposeList([]);
};


/**
 * repeated float arf32CurDRPose = 6;
 * @return {!Array<number>}
 */
proto.vpdata.state.VPState_t.prototype.getArf32curdrposeList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 6));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.vpdata.state.VPState_t} returns this
 */
proto.vpdata.state.VPState_t.prototype.setArf32curdrposeList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.vpdata.state.VPState_t} returns this
 */
proto.vpdata.state.VPState_t.prototype.addArf32curdrpose = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.vpdata.state.VPState_t} returns this
 */
proto.vpdata.state.VPState_t.prototype.clearArf32curdrposeList = function() {
  return this.setArf32curdrposeList([]);
};


/**
 * optional vp.tracking.VPStatusTrackingMode eVPStatusTrackingMode = 7;
 * @return {!proto.vp.tracking.VPStatusTrackingMode}
 */
proto.vpdata.state.VPState_t.prototype.getEvpstatustrackingmode = function() {
  return /** @type {!proto.vp.tracking.VPStatusTrackingMode} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.vp.tracking.VPStatusTrackingMode} value
 * @return {!proto.vpdata.state.VPState_t} returns this
 */
proto.vpdata.state.VPState_t.prototype.setEvpstatustrackingmode = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};


/**
 * repeated vp.tracking.FramePoseInfo_t stFramePoseInfoSet = 8;
 * @return {!Array<!proto.vp.tracking.FramePoseInfo_t>}
 */
proto.vpdata.state.VPState_t.prototype.getStframeposeinfosetList = function() {
  return /** @type{!Array<!proto.vp.tracking.FramePoseInfo_t>} */ (
    jspb.Message.getRepeatedWrapperField(this, vp_tracking_pb.FramePoseInfo_t, 8));
};


/**
 * @param {!Array<!proto.vp.tracking.FramePoseInfo_t>} value
 * @return {!proto.vpdata.state.VPState_t} returns this
*/
proto.vpdata.state.VPState_t.prototype.setStframeposeinfosetList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.vp.tracking.FramePoseInfo_t=} opt_value
 * @param {number=} opt_index
 * @return {!proto.vp.tracking.FramePoseInfo_t}
 */
proto.vpdata.state.VPState_t.prototype.addStframeposeinfoset = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.vp.tracking.FramePoseInfo_t, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.vpdata.state.VPState_t} returns this
 */
proto.vpdata.state.VPState_t.prototype.clearStframeposeinfosetList = function() {
  return this.setStframeposeinfosetList([]);
};


/**
 * optional vp.tracking.KalmanFilter_t stLinearVelocityKF = 9;
 * @return {?proto.vp.tracking.KalmanFilter_t}
 */
proto.vpdata.state.VPState_t.prototype.getStlinearvelocitykf = function() {
  return /** @type{?proto.vp.tracking.KalmanFilter_t} */ (
    jspb.Message.getWrapperField(this, vp_tracking_pb.KalmanFilter_t, 9));
};


/**
 * @param {?proto.vp.tracking.KalmanFilter_t|undefined} value
 * @return {!proto.vpdata.state.VPState_t} returns this
*/
proto.vpdata.state.VPState_t.prototype.setStlinearvelocitykf = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vpdata.state.VPState_t} returns this
 */
proto.vpdata.state.VPState_t.prototype.clearStlinearvelocitykf = function() {
  return this.setStlinearvelocitykf(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vpdata.state.VPState_t.prototype.hasStlinearvelocitykf = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional vp.tracking.KalmanFilter_t stVPSPoseKF = 10;
 * @return {?proto.vp.tracking.KalmanFilter_t}
 */
proto.vpdata.state.VPState_t.prototype.getStvpsposekf = function() {
  return /** @type{?proto.vp.tracking.KalmanFilter_t} */ (
    jspb.Message.getWrapperField(this, vp_tracking_pb.KalmanFilter_t, 10));
};


/**
 * @param {?proto.vp.tracking.KalmanFilter_t|undefined} value
 * @return {!proto.vpdata.state.VPState_t} returns this
*/
proto.vpdata.state.VPState_t.prototype.setStvpsposekf = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vpdata.state.VPState_t} returns this
 */
proto.vpdata.state.VPState_t.prototype.clearStvpsposekf = function() {
  return this.setStvpsposekf(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vpdata.state.VPState_t.prototype.hasStvpsposekf = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * repeated vp.tracking.Param_t stParamSet = 11;
 * @return {!Array<!proto.vp.tracking.Param_t>}
 */
proto.vpdata.state.VPState_t.prototype.getStparamsetList = function() {
  return /** @type{!Array<!proto.vp.tracking.Param_t>} */ (
    jspb.Message.getRepeatedWrapperField(this, vp_tracking_pb.Param_t, 11));
};


/**
 * @param {!Array<!proto.vp.tracking.Param_t>} value
 * @return {!proto.vpdata.state.VPState_t} returns this
*/
proto.vpdata.state.VPState_t.prototype.setStparamsetList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.vp.tracking.Param_t=} opt_value
 * @param {number=} opt_index
 * @return {!proto.vp.tracking.Param_t}
 */
proto.vpdata.state.VPState_t.prototype.addStparamset = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.vp.tracking.Param_t, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.vpdata.state.VPState_t} returns this
 */
proto.vpdata.state.VPState_t.prototype.clearStparamsetList = function() {
  return this.setStparamsetList([]);
};


goog.object.extend(exports, proto.vpdata.state);
